services:
  bot:
    build: .
    container_name: basket_bot
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:18
    container_name: basket_bot_db
    restart: always
    env_file: .env
    ports:
      - ${POSTGRES_DB_PORTS}
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    container_name: basket_bot_adminer
    restart: always
    env_file: .env
    ports:
      - ${ADMINER_PORTS}

volumes:
  postgres_data:
